version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
  
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/app

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'letmein'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'test'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysqldata:
